version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: delivery_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/deliveryDB
    depends_on:
      - mongo

volumes:
  mongo-data:
